import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import { Toaster } from "@/components/ui/Sonner"
import { MSWProvider } from '@/mocks/MSWProvider'
import "./globals.css";

if (process.env.NODE_ENV === 'development' && typeof window === 'undefined') {
  const { server } = require('@/mocks/node')
  server.listen({ onUnhandledRequest: 'bypass' })
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <MSWProvider>{children}</MSWProvider>
          
          <Toaster 
            position="top-center"
            richColors
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
